const product=(name,details,type,area,asset,row=0,layout='grid')=>({name,details,type,area,asset,row,layout});
const paired=(asset,type,area,a,b)=>[product(a[0],a[1],type,area,asset,0),product(b[0],b[1],type,area,asset,1)];
const P='/assets/images/products/';
const dhaniakhaliProduct=(id,name,design,colors,count,price=45,availability='Available',assetVersion='')=>({
  id,name,design,colors,type:'dhaniakhali',area:'all',layout:'photos',price:'Contact us for price',priceValue:price,
  availability,
  details:`Pure cotton · ${colors.join(', ')} · GI-tagged Dhaniakhali weave`,
  images:Array.from({length:count},(_,index)=>{
    const number=String(index+1).padStart(2,'0');
    const version=assetVersion?`?v=${assetVersion}`:'';
    return {card:`${P}dhaniakhali/${id}/${number}-card.jpg${version}`,large:`${P}dhaniakhali/${id}/${number}-large.jpg${version}`};
  })
});
const banarasiProduct=(id,name,design,colors,count)=>({
  id,name,design,colors,type:'banarasi',area:'all',layout:'photos',price:'Contact us for price',
  details:`Pure silk · ${colors.join(', ')} · GI-tagged Banaras Brocades and Sarees`,
  images:Array.from({length:count},(_,index)=>{
    const number=String(index+1).padStart(2,'0');
    return {card:`${P}banarasi/${id}/${number}-large.jpg?v=4`,large:`${P}banarasi/${id}/${number}-large.jpg?v=4`};
  })
});
const regionPages={
  bengal:{eyebrow:'West Bengal · Bangladesh · The wider Bengal cultural region',title:'Bengal Handloom',intro:'Across West Bengal and Bangladesh—and among Bengali communities in Tripura and Assam’s Barak Valley—weaving traditions range from crisp everyday cotton and fine muslin to narrative silk.',board:'/assets/images/catalogue/regions/bengal-board.webp',types:[['Gorod','gorod'],['Dhaniakhali','dhaniakhali'],['Baluchari','baluchari'],['Phulia','phulia'],['Bengal Kalakshetra','kalakshetra']],cards:[
    ...paired(P+'gorod-products.webp','gorod','all',['Shankha Ivory Gorod','Silk · Red temple border'],['Sindoor Cream Gorod','Silk · Fine red paar']),
    dhaniakhaliProduct('DHA-001','Fish Motif Dhaniakhali','Fish Motif',['White','Red'],1),
    dhaniakhaliProduct('DHA-002','Fish Motif Dhaniakhali','Fish Motif',['White','Red','Black'],1),
    dhaniakhaliProduct('DHA-003','Fish Motif Dhaniakhali','Fish Motif',['White','Red','Basanti Yellow'],1,45,'Sold Out'),
    dhaniakhaliProduct('DHA-004','Fish Motif Dhaniakhali','Fish Motif',['White','Red','Yellow'],1),
    dhaniakhaliProduct('DHA-005','Ikat Border Dhaniakhali','Ikat Border',['White','Red'],2,45,'Sold Out'),
    dhaniakhaliProduct('DHA-006','Traditional Dhaniakhali','Traditional',['White','Red'],3),
    dhaniakhaliProduct('DHA-007','Traditional Dhaniakhali','Traditional',['White','Red','Black'],2),
    dhaniakhaliProduct('DHA-008','Traditional Dhaniakhali','Traditional',['Light Pink','Pinkish Red'],2),
    dhaniakhaliProduct('DHA-009','Traditional Dhaniakhali','Traditional',['Light Pink','Rose Red'],3),
    dhaniakhaliProduct('DHA-010','Ikat Border Dhaniakhali','Ikat Border',['Yellow','Red'],1,45,'Sold Out'),
    dhaniakhaliProduct('DHA-011','Ikat Border Dhaniakhali','Ikat Border',['Black','Yellow'],1),
    dhaniakhaliProduct('DHA-012','Ikat Border Dhaniakhali','Ikat Border',['Black','Red'],1),
    dhaniakhaliProduct('DHA-013','Ikat Border Dhaniakhali','Ikat Border',['Grey','Blue'],1),
    dhaniakhaliProduct('DHA-014','Inch Par Dhaniakhali','Inch Par',['Light Mauve','Wine'],1),
    dhaniakhaliProduct('DHA-015','Traditional Dhaniakhali','Traditional',['Grey','Red','Black','White'],3),
    dhaniakhaliProduct('DHA-016','Traditional Dhaniakhali','Traditional',['Navy Blue','Red','Yellow'],1),
    dhaniakhaliProduct('DHA-017','Fish Motif Dhaniakhali','Fish Motif',['Black','Red','Yellow'],2),
    dhaniakhaliProduct('DHA-018','Fish Motif Dhaniakhali','Fish Motif',['Black','White'],3),
    dhaniakhaliProduct('DHA-019','Fish Motif Dhaniakhali','Fish Motif',['Black','White'],3),
    dhaniakhaliProduct('DHA-020','Fish Motif Dhaniakhali','Fish Motif',['White','Black'],1,45,'Available','2'),
    dhaniakhaliProduct('DHA-021','Traditional Dhaniakhali','Traditional',['Navy Blue','Yellow'],1),
    product('Ranga Oxblood Baluchari','Silk · Narrative figured pallu','baluchari','all',P+'baluchari-oxblood-views.webp',0,'strip'),product('Bonolata Olive Baluchari','Silk · Figured floral pallu','baluchari','all',P+'baluchari-olive-views.webp',0,'strip'),
    ...paired(P+'phulia-products.webp','phulia','all',['Sage Rekha Phulia','Cotton · Contemporary border'],['Megh Blue Phulia','Cotton · Fine buti']),
    ...paired(P+'kalakshetra-products.webp','kalakshetra','all',['Terracotta Lok Kalakshetra','Cotton-silk · Folk motifs'],['Indigo Bagan Kalakshetra','Cotton-silk · Botanical motifs'])]},
  odisha:{eyebrow:'Odisha · Eastern India',title:'Odisha Handloom',intro:'A focused presentation of Dhalapathar’s rooted cotton tradition and distinctive extra-weft geometry.',board:'/assets/images/catalogue/regions/odisha-board.webp',types:[['Dhalapathar','dhalapathar']],cards:[
    ...paired(P+'dhalapathar-products.webp','dhalapathar','all',['Mati Rekha Dhalapathar','Cotton · Extra-weft geometry'],['Neel Rekha Dhalapathar','Cotton · Graphic border'])]},
  'south-india':{eyebrow:'Karnataka · Telangana · Southern India',title:'South Indian Handloom',intro:'From Ilkal and Patteda Anchu in Karnataka to Narayanpet in Telangana, these traditions unite graphic borders, ingenious construction and cloth made for warm climates.',board:'/assets/images/catalogue/regions/south-india-board.webp',types:[['Ilkal','ilkal'],['Narayanpet','narayanpet'],['Patteda Anchu','patteda-anchu']],cards:[
    ...paired(P+'ilkal-products.webp','ilkal','all',['Rakta Tope Teni Ilkal','Cotton-silk · Tope teni border'],['Neel Maroon Ilkal','Cotton-silk · Contrast pallu']),...paired(P+'narayanpet-products.webp','narayanpet','all',['Haldi Temple Narayanpet','Cotton-silk · Temple border'],['Teal Checks Narayanpet','Cotton-silk · Fine checks']),...paired(P+'patteda-anchu-products.webp','patteda-anchu','all',['Kora Anchu Patteda','Handspun cotton · Heritage border'],['Charcoal Anchu Patteda','Handspun cotton · Narrow stripe'])]},
  banarasi:{eyebrow:'Varanasi · Uttar Pradesh',title:'Banarasi',intro:'Lustrous silk, intricate zari and garden-like jaal patterns woven in one of India’s most storied textile cities.',types:[['Banarasi','banarasi']],cards:[
    banarasiProduct('BAN-001','Traditional Banarasi — Red','Traditional',['Red'],3),
    banarasiProduct('BAN-002','Traditional Banarasi — Emerald Green','Traditional',['Emerald Green'],2)
  ]},
  kanchipuram:{eyebrow:'Kanchipuram · Tamil Nadu',title:'Kanchipuram',intro:'Architectural borders, substantial silk and the celebrated korvai join give Kanchipuram sarees their unmistakable presence.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:1,types:[['Kanchipuram','kanchipuram']],cards:paired(P+'kanchipuram-products.webp','kanchipuram','all',['Maroon Temple Korvai','Mulberry silk · Contrast border'],['Peacock Magenta Korvai','Mulberry silk · Figured pallu'])},
  maheshwari:{eyebrow:'Maheshwar · Madhya Pradesh',title:'Maheshwari',intro:'Light silk-cotton, elegant stripes and reversible borders carry the refined geometry of Maheshwar’s weaving heritage.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:2,types:[['Maheshwari','maheshwari']],cards:paired(P+'maheshwari-products.webp','maheshwari','all',['Sage Chandrakala','Silk-cotton · Zari border'],['Baingani Checks','Silk-cotton · Reversible border'])}
};
const categoryStories={
  bengal:{
    dhaniakhali:{kicker:'Hooghly district · West Bengal',title:'The quiet rhythm of Bengal cotton',lead:'Crisp, enduring and unmistakably grounded in place.',facts:[['Cloth','Handloom cotton'],['Known for','Distinctive woven borders'],['Heritage','Geographical Indication protected']],paragraphs:[
      'Dhaniakhali is a traditional cotton handloom saree from the Hooghly district of West Bengal, with a weaving heritage that stretches back generations. Known for its crisp cotton, distinctive borders, and everyday elegance, the saree developed around the weaving communities of Dhaniakhali and the surrounding villages.',
      'Originally valued as a practical cotton saree for Bengal’s warm climate, Dhaniakhali became known for its durability, comfort, and understated beauty. Traditionally woven on handlooms, its character comes from the slight texture of the cloth and the rhythm of the woven border rather than elaborate ornamentation.',
      'Today, Dhaniakhali remains part of Bengal’s living handloom tradition and is protected by a Geographical Indication (GI) tag, recognizing its connection to the region and its weaving heritage.'
    ]}
  }
};
const editorial=(kicker,title,lead,facts,paragraphs)=>({kicker,title,lead,facts,paragraphs});
Object.assign(categoryStories.bengal,{
  gorod:editorial('West Bengal · Ceremonial silk tradition','Ivory silk, edged in red','Ceremonial restraint expressed through cloth.',[['Cloth','Silk'],['Signature','Red border on an ivory body'],['Character','Light, luminous, understated']],['Gorod is recognized for an ivory or undyed silk ground framed by a red border. Its beauty lies in restraint: the natural glow of silk, a decisive paar and a composition that allows the cloth itself to remain central.','Closely associated with Bengal’s ceremonial wardrobe, Gorod is often chosen for religious and festive occasions. Handloom texture keeps the surface alive, giving an apparently simple saree quiet depth.']),
  baluchari:editorial('Bishnupur · West Bengal','A pallu that tells a story','Silk becomes a woven picture gallery.',[['Cloth','Figured silk'],['Signature','Narrative pallu panels'],['Heritage','Geographical Indication protected']],['Baluchari sarees are celebrated for elaborate pallus woven with figurative scenes, floral frames and architectural borders. Rather than relying on embroidery, their imagery is constructed within the weave.','The tradition is strongly associated with Bishnupur. Each composition rewards close looking: borders establish the frame while the pallu carries the saree’s central narrative.']),
  phulia:editorial('Nadia district · West Bengal','Tradition in a lighter register','Fine cotton shaped by a contemporary weaving centre.',[['Cloth','Fine handloom cotton'],['Place','Phulia and the Nadia weaving belt'],['Character','Light, precise, versatile']],['Phulia is an important handloom centre in Nadia district, known for fine cotton sarees that balance inherited Bengal techniques with evolving design. Crisp borders, restrained motifs and breathable cloth give the weave its everyday versatility.','The saree’s identity comes from the intelligence of proportion: body, border and pallu are composed to feel light without becoming visually slight.']),
  kalakshetra:editorial('Bengal · Art-led handloom','The loom as a drawing surface','Folk memory and graphic rhythm meet in cloth.',[['Cloth','Cotton or cotton-silk'],['Signature','Art-led figurative motifs'],['Character','Graphic, narrative, expressive']],['Bengal Kalakshetra sarees bring an art-led sensibility to regional handloom, using woven or textile-applied motifs inspired by folk imagery, landscape and everyday cultural memory.','The emphasis is expressive rather than uniform. Borders and pallus become fields for drawing with thread, allowing each saree to carry a distinct visual voice.'])
});
categoryStories.odisha={dhalapathar:editorial('Khurda district · Odisha','Geometry with a village memory','A distinctive cotton tradition rooted in Dhalapathar.',[['Cloth','Handloom cotton'],['Signature','Extra-warp and extra-weft patterning'],['Heritage','Geographical Indication protected']],['Dhalapathar is associated with a weaving community in Odisha’s Khurda district. Its textile vocabulary is known for strong geometric arrangement and pattern created through carefully controlled supplementary threads.','The tradition extends beyond sarees to furnishing textiles, yet the same disciplined construction remains visible: a sturdy cotton ground animated by borders, bands and culturally rooted motifs.'])};
categoryStories['south-india']={
  ilkal:editorial('Ilkal · Bagalkot district · Karnataka','A border joined with ingenuity','Bold colour and the distinctive tope teni construction.',[['Cloth','Cotton body with silk or art-silk pallu'],['Signature','Tope teni joining technique'],['Heritage','Geographical Indication protected']],['Ilkal sarees are distinguished by the structural relationship between body, border and pallu. The celebrated tope teni technique joins separately prepared warps, creating a decisive transition in colour and material.','Graphic stripes and temple-like forms give the pallu a strong cadence, while the cotton body keeps the saree practical and wearable.']),
  narayanpet:editorial('Narayanpet district · Telangana','Checks, stripes and temple edges','A compact southern classic made for movement.',[['Cloth','Cotton or silk-cotton'],['Signature','Checked body and temple border'],['Character','Light, graphic, practical']],['Narayanpet sarees are known for checked or striped fields, contrast borders and small temple-inspired forms. Their structure is clear and rhythmic, making them easy to recognize without elaborate surface ornament.','Traditionally valued for comfort and durability, the weave brings together an everyday lightness and a distinctly southern graphic language.']),
  'patteda-anchu':editorial('Northern Karnataka','A narrow border, precisely placed','Handloom cotton with an austere, enduring beauty.',[['Cloth','Handloom cotton'],['Signature','Narrow anchu border'],['Character','Minimal, breathable, grounded']],['Patteda Anchu is a northern Karnataka cotton saree tradition recognized by its narrow border and direct, functional beauty. The cloth is breathable and the composition intentionally spare.','Its appeal comes from proportion and texture rather than excess decoration—a reminder that handloom character can be most powerful when the design is reduced to its essentials.'])
};
categoryStories.banarasi={banarasi:editorial('Varanasi · Uttar Pradesh','A garden drawn in silk and zari','Lustre, density and extraordinary brocade skill.',[['Cloth','Silk brocade'],['Signature','Zari, jaal and butidar patterning'],['Heritage','Geographical Indication protected']],['Banarasi sarees are woven in and around Varanasi and are celebrated for richly structured brocade. Floral jaals, individual butis and metallic zari are organized through techniques that can range from delicate to architectural.','The finest examples reveal their complexity gradually: first as lustre and pattern, then as a close conversation between ground cloth, supplementary threads and the disciplined hand of the weaver.'])};
categoryStories.kanchipuram={kanchipuram:editorial('Kanchipuram · Tamil Nadu','Silk with architectural presence','Temple geometry, saturated colour and the strength of korvai.',[['Cloth','Mulberry silk'],['Signature','Contrast korvai border'],['Heritage','Geographical Indication protected']],['Kanchipuram sarees are known for substantial silk, saturated colour and borders that often echo the geometry of temple architecture. In korvai construction, contrasting sections are joined with exceptional control.','The result is both visual and structural: a saree with weight, clarity and a pallu designed to hold its presence across generations.'])};
categoryStories.maheshwari={maheshwari:editorial('Maheshwar · Madhya Pradesh','Lightness framed by geometry','Reversible borders and an elegant silk-cotton balance.',[['Cloth','Silk-cotton'],['Signature','Reversible border and striped pallu'],['Character','Light, polished, architectural']],['Maheshwari sarees are associated with the weaving town of Maheshwar and are valued for their light silk-cotton body, fine stripes, checks and elegantly controlled borders.','Many examples use a reversible border, giving both sides a finished appearance. The weave feels refined without heaviness, carrying the measured geometry of its place of origin.'])};
const mastCopy={
  bengal:{
    gorod:['West Bengal · Ceremonial silk tradition','Gorod','Ivory or undyed silk, traditionally framed by a red border, gives this ceremonial West Bengal tradition its quiet distinction.'],
    dhaniakhali:['Dhaniakhali · Hooghly district · West Bengal','Dhaniakhali','Crisp handloom cotton and distinctive woven borders carry the everyday elegance of Dhaniakhali and its surrounding weaving villages.'],
    baluchari:['Baluchar, Murshidabad · Bishnupur, Bankura · West Bengal','Baluchari','Originating in Baluchar and now strongly associated with Bishnupur, Baluchari silk turns the pallu into a field of woven narrative.'],
    phulia:['Phulia · Nadia district · West Bengal','Phulia','Fine cotton, precise borders and an evolving design language distinguish this important weaving centre in West Bengal’s Nadia district.'],
    kalakshetra:['West Bengal · Art-led handloom','Bengal Kalakshetra','An expressive, art-led strand of Bengal handloom in which folk memory, botanical forms and graphic storytelling meet cloth.']
  },
  odisha:{dhalapathar:['Dhalapathar · Khurda district · Odisha','Dhalapathar','A rooted Odisha cotton tradition known for disciplined supplementary-thread patterning, geometric bands and culturally resonant motifs.']},
  'south-india':{
    ilkal:['Ilkal · Bagalkot district · Karnataka','Ilkal','Bold colour and the distinctive tope teni joining technique define this celebrated Karnataka handloom tradition.'],
    narayanpet:['Narayanpet district · Telangana','Narayanpet','Checked and striped fields, contrast borders and compact temple forms give Narayanpet sarees their recognizable rhythm.'],
    'patteda-anchu':['Northern Karnataka','Patteda Anchu','A revived northern Karnataka cotton tradition whose narrow border, breathable cloth and measured proportions express purposeful simplicity.']
  },
  banarasi:{banarasi:['Varanasi and its surrounding weaving region · Uttar Pradesh','Banarasi','Rich brocade, floral jaals, butis and metallic zari reflect the disciplined weaving culture of Varanasi and nearby centres.']},
  kanchipuram:{kanchipuram:['Kanchipuram · Tamil Nadu','Kanchipuram','Substantial silk, saturated colour and structurally joined borders give Kanchipuram sarees their architectural presence.']},
  maheshwari:{maheshwari:['Maheshwar · Madhya Pradesh','Maheshwari','Light silk-cotton, restrained geometry and reversible borders carry the refined weaving identity of Maheshwar.']}
};
const key=document.body.dataset.region,info=regionPages[key],main=document.querySelector('#main-content');
if(info&&main){
  const panelStyle=info.panel==null?'':`style="width:300%;max-width:none;transform:translateX(-${info.panel*33.333}%);object-fit:cover"`;
  const featuredIds={bengal:{all:['DHA-003','DHA-005','DHA-007'],dhaniakhali:['DHA-003','DHA-014','DHA-015']},banarasi:{all:['BAN-001','BAN-002'],banarasi:['BAN-001','BAN-002']}};
  const featureFor=id=>{const item=info.cards.find(card=>card.id===id),image=item?.images?.[0]?.card;if(!item||!image)return null;return [id,labelForType(item.type),item.design||item.name,image]};
  const labelForType=slug=>info.types.find(([,value])=>value===slug)?.[0]||info.title;
  const buildMastVisual=slug=>{
    const ids=featuredIds[key]?.[slug]||[],features=ids.map(featureFor).filter(Boolean),title=slug==='all'?info.title:(mastCopy[key]?.[slug]?.[1]||labelForType(slug));
    if(features.length)return `<div class="region-board bengal-feature-board${features.length===2?' two-up':''}" aria-label="Featured ${title} sarees">${features.map(([id,weave,label,image])=>`<a href="#${slug}" data-feature-product="${id}" aria-label="View ${label} ${weave}, ${id}"><img src="${image}" alt="${label} ${weave} saree"><span><small>${weave}</small>${label}</span></a>`).join('')}</div>`;
    const backdrop=info.board?`<img class="region-editorial-image" src="${info.board}" alt="" ${panelStyle}>`:'';
    return `<div class="region-board region-coming-board has-editorial-image" aria-label="${title} collection in preparation">${backdrop}<span class="loom-line line-one"></span><span class="loom-line line-two"></span><div><p>Collection in preparation</p><strong>${title}</strong><small>We are selecting and photographing authentic pieces from this tradition.</small></div></div>`
  };
  const mastVisual=buildMastVisual('all');
  const areaFilters=info.groups?`<div class="filter-level" data-area-filters><p>1 · Choose an area</p><div><button data-area="all" aria-pressed="true">All Bengal</button>${info.groups.map(([name,slug])=>`<button data-area="${slug}" aria-pressed="false">${name}</button>`).join('')}</div></div>`:'';
  const typeFilters=`<div class="filter-level" data-type-filters><p>${info.groups?'2 · Choose a weave':'Filter by weave'}</p><div><a href="#all" data-filter="all" data-area="all">All ${info.title.replace(' Handloom','')}</a>${info.types.filter(([,slug])=>slug!=='all').map(([name,slug,area])=>`<a id="filter-${slug}" href="#${slug}" data-filter="${slug}" data-area="${area||'all'}">${name}</a>`).join('')}</div></div>`;
  const realProducts=info.cards.filter(card=>card.images),facetType=realProducts[0]?.type,facetLabel=info.types.find(([,slug])=>slug===facetType)?.[0]||info.title,designs=[...new Set(realProducts.map(card=>card.design).filter(Boolean))],colors=[...new Set(realProducts.flatMap(card=>card.colors||[]))],availabilityOptions=[...new Set(realProducts.map(card=>card.availability||'Available'))];
  const facetMarkup=realProducts.length?`<aside class="product-facets without-price" data-product-facets hidden aria-label="Filter ${facetLabel} products"><div class="facet-intro"><div><p class="eyebrow">Refine ${facetLabel}</p><h3>Find your saree</h3></div><button type="button" data-clear-facets>Clear filters</button></div><div class="facet-primary"><fieldset><legend>Design</legend><div class="facet-options"><button type="button" data-facet="design" data-value="all" aria-pressed="true">All designs</button>${designs.map(value=>`<button type="button" data-facet="design" data-value="${value}" aria-pressed="false">${value}</button>`).join('')}</div></fieldset><fieldset><legend>Availability</legend><div class="facet-options"><button type="button" data-facet="availability" data-value="all" aria-pressed="true">All</button>${availabilityOptions.map(value=>`<button type="button" data-facet="availability" data-value="${value}" aria-pressed="false">${value}</button>`).join('')}</div></fieldset></div><fieldset class="facet-color"><legend>Color</legend><div class="facet-options"><button type="button" data-facet="color" data-value="all" aria-pressed="true">All colors</button>${colors.map(value=>`<button type="button" data-facet="color" data-value="${value}" aria-pressed="false"><span class="color-dot" data-color="${value.toLowerCase().replaceAll(' ','-')}"></span>${value}</button>`).join('')}</div></fieldset><p class="facet-results" data-facet-results aria-live="polite"></p></aside>`:'';
  const comingMarkup=`<div class="collection-coming-soon" data-coming-soon hidden><p class="eyebrow">Collection in preparation</p><h3>Something beautiful is on its way.</h3><p>We are thoughtfully assembling this collection and photographing every piece. Please stay tuned for the first release.</p><a href="/index.html#contact">Join the first look <span aria-hidden="true">↗</span></a></div>`;
  const cardMarkup=info.cards.map((c,index)=>{
    if(!c.images)return '';
    const views=c.images||[0,1,2].map(view=>({card:c.asset,view})),hasGallery=views.length>1;
    const images=views.map((image,i)=>`<img class="sheet-view ${c.images?'photo-view':`sheet-view-${image.view}`}${i===0?' is-active':''}" src="${image.card}" alt="${i===0?`${c.name} product photograph`:''}" aria-hidden="${i!==0}" loading="lazy">`).join('');
    const soldOut=c.availability==='Sold Out';
    return `<article class="preview-card${c.images?' real-product':''}${soldOut?' is-sold-out':''}" data-product-index="${index}" data-type="${c.type}" data-area="${c.area}" data-design="${c.design||''}" data-colors="${c.colors?.join('|')||''}" data-availability="${c.availability||'Available'}" tabindex="0" aria-label="Open ${c.name} details${soldOut?', sold out':''}"><div class="preview-image product-sheet" data-layout="${c.layout}" data-row="${c.row||0}">${images}<span class="preview-badge">${c.id||'Concept'}</span>${soldOut?'<span class="product-status-badge">Sold out</span>':''}${hasGallery?`<div class="preview-arrows"><button type="button" data-preview-previous aria-label="Previous view">‹</button><button type="button" data-preview-next aria-label="Next view">›</button></div><span class="preview-count" aria-hidden="true">1 / ${views.length}</span>`:''}</div><h3>${c.name}</h3><p>${c.details} · <strong>${c.price||'Contact us for price'}</strong></p><span class="preview-open">View details <span aria-hidden="true">↗</span></span></article>`;
  }).join('');
  main.innerHTML=`<section class="region-mast"><div data-mast-copy aria-live="polite"><p class="eyebrow">${info.eyebrow}</p><h1>${info.title}</h1><p>${info.intro}</p></div><div data-mast-visual>${mastVisual}</div></section><section class="collection-filters"><div class="filter-heading"><p class="eyebrow">Refine the collection</p><h2>Find your weave</h2><p data-filter-summary aria-live="polite"></p></div>${areaFilters}${typeFilters}</section><section class="category-story" data-category-story hidden></section><section class="preview-section" id="collection"><div class="preview-head"><div><p class="eyebrow">Collection preview</p><h2 data-results-title>All ${info.title}</h2></div><p class="demo-note" data-collection-note>Concept imagery · Final prices coming soon</p></div>${facetMarkup}${comingMarkup}<div class="preview-grid">${cardMarkup}</div></section><dialog class="product-quick-view" aria-labelledby="quick-view-title"><button class="quick-view-close" type="button" aria-label="Close product details">×</button><div class="quick-view-layout"><div class="quick-view-media"><div class="quick-view-stage product-sheet"><div class="quick-view-images"></div><button class="quick-view-arrow previous" type="button" aria-label="Previous product view">‹</button><button class="quick-view-arrow next" type="button" aria-label="Next product view">›</button><span class="quick-view-count" aria-live="polite"></span></div><div class="quick-view-thumbs" aria-label="Choose a product view"></div></div><div class="quick-view-copy"><p class="eyebrow" data-quick-view-kicker></p><h2 id="quick-view-title"></h2><p class="quick-view-details"></p><p class="quick-view-price"></p><p class="quick-view-availability" aria-live="polite"></p><div class="quick-view-rule"></div><p data-quick-view-description></p><a class="button primary" href="/index.html#contact"><span data-quick-view-action>Enquire about this saree</span> <span aria-hidden="true">↘</span></a><p class="quick-view-note"></p></div></div></dialog>`;
  const cards=[...main.querySelectorAll('.preview-card')],typeLinks=[...main.querySelectorAll('[data-filter]')],areaButtons=[...main.querySelectorAll('[data-area-filters] button')],summary=main.querySelector('[data-filter-summary]'),resultsTitle=main.querySelector('[data-results-title]'),storySection=main.querySelector('[data-category-story]'),mastCopyElement=main.querySelector('[data-mast-copy]'),mastVisualElement=main.querySelector('[data-mast-visual]'),facets=main.querySelector('[data-product-facets]'),comingSoon=main.querySelector('[data-coming-soon]');let selectedArea='all',selectedType='all',selectedDesign='all',selectedColor='all',selectedAvailability='all';
  main.querySelector('[data-collection-note]').textContent=key==='bengal'?'Real Dhaniakhali photography · More collections arriving soon':key==='banarasi'?'Real Banarasi photography · Price available on request':'New collection in preparation';
  const labelFor=slug=>info.types.find(([,v])=>v===slug)?.[0]||info.groups?.find(([,v])=>v===slug)?.[0]||`All ${info.title}`;
  const renderMast=slug=>{const copy=slug==='all'?[info.eyebrow,info.title,info.intro]:(mastCopy[key]?.[slug]||[categoryStories[key]?.[slug]?.kicker||info.eyebrow,labelFor(slug),categoryStories[key]?.[slug]?.lead||info.intro]);mastCopyElement.innerHTML=`<p class="eyebrow">${copy[0]}</p><h1>${copy[1]}</h1><p>${copy[2]}</p>`;mastVisualElement.innerHTML=buildMastVisual(slug)};
  const renderCategoryStory=slug=>{const story=categoryStories[key]?.[slug];if(!story){storySection.hidden=true;storySection.innerHTML='';return}storySection.innerHTML=`<div class="category-story-heading"><p class="eyebrow">${story.kicker}</p><h2>${labelFor(slug)}</h2><h3>${story.title}</h3><p class="category-story-lead">${story.lead}</p></div><div class="category-story-body">${story.paragraphs.map((paragraph,index)=>`<p${index===0?' class="drop-cap"':''}>${paragraph}</p>`).join('')}</div><dl class="category-story-facts">${story.facts.map(([term,value])=>`<div><dt>${term}</dt><dd>${value}</dd></div>`).join('')}</dl><div class="category-story-action"><a class="category-story-jump" href="#collection">View the collection <span aria-hidden="true">↓</span></a></div><span class="category-story-mark" aria-hidden="true">ধ</span>`;storySection.hidden=false;storySection.querySelector('.category-story-jump').onclick=event=>{event.preventDefault();main.querySelector('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}};
  const applyProductFacets=()=>{if(!facets||selectedType!==facetType)return;let count=0;cards.filter(card=>card.dataset.type===facetType).forEach(card=>{const designMatch=selectedDesign==='all'||card.dataset.design===selectedDesign,colorMatch=selectedColor==='all'||card.dataset.colors.split('|').includes(selectedColor),availabilityMatch=selectedAvailability==='all'||card.dataset.availability===selectedAvailability,show=designMatch&&colorMatch&&availabilityMatch;card.hidden=!show;if(show)count++});facets.querySelector('[data-facet-results]').textContent=`${count} of ${realProducts.length} ${count===1?'saree':'sarees'}`;summary.textContent=`Showing ${count} ${count===1?'saree':'sarees'} · ${facetLabel}`};
  const resetProductFacets=()=>{selectedDesign='all';selectedColor='all';selectedAvailability='all';if(!facets)return;facets.querySelectorAll('[data-facet]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.value==='all')));applyProductFacets()};
  function applyFilter(value,{updateUrl=false}={}){const typeExists=info.types.some(([,s])=>s===value),areaExists=info.groups?.some(([,s])=>s===value);selectedType=typeExists?value:'all';if(areaExists)selectedArea=value;else if(typeExists&&value!=='all')selectedArea=info.types.find(([,s])=>s===value)?.[2]||'all';else selectedArea='all';areaButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.area===selectedArea)));typeLinks.forEach(l=>{const belongs=selectedArea==='all'||l.dataset.area==='all'||l.dataset.area===selectedArea;l.hidden=!belongs;l.classList.toggle('is-active',selectedType===l.dataset.filter||(selectedType==='all'&&l.dataset.filter==='all'));l.setAttribute('aria-current',l.classList.contains('is-active')?'true':'false')});let count=0;cards.forEach(c=>{const show=selectedType!=='all'?c.dataset.type===selectedType:selectedArea==='all'||c.dataset.area===selectedArea;c.hidden=!show;if(show)count++});if(facets){facets.hidden=selectedType!==facetType;if(selectedType===facetType)applyProductFacets()}const chosen=selectedType!=='all'?labelFor(selectedType):selectedArea!=='all'?labelFor(selectedArea):`All ${info.title}`;resultsTitle.textContent=chosen;comingSoon.hidden=count>0;if(selectedType!==facetType)summary.textContent=count?`Showing ${count} ${count===1?'saree':'sarees'} · ${chosen}`:`Collection in preparation · ${chosen}`;renderMast(selectedType);renderCategoryStory(selectedType);if(updateUrl)history.replaceState(null,'',value==='all'?location.pathname:`#${value}`)}
  if(facets){facets.querySelectorAll('[data-facet]').forEach(button=>button.onclick=()=>{const facet=button.dataset.facet,value=button.dataset.value;if(facet==='design')selectedDesign=value;else if(facet==='color')selectedColor=value;else selectedAvailability=value;facets.querySelectorAll(`[data-facet="${facet}"]`).forEach(option=>option.setAttribute('aria-pressed',String(option===button)));applyProductFacets()});facets.querySelector('[data-clear-facets]').onclick=resetProductFacets}
  cards.forEach(card=>{const gallery=card.querySelector('.preview-image'),images=[...gallery.querySelectorAll('.sheet-view')],count=gallery.querySelector('.preview-count'),fine=matchMedia('(hover: hover) and (pointer: fine)'),reduced=matchMedia('(prefers-reduced-motion: reduce)');if(images.length<2)return;let current=0,timer,touchStart=0;const show=index=>{current=(index+images.length)%images.length;images.forEach((img,i)=>{const active=i===current;img.classList.toggle('is-active',active);img.setAttribute('aria-hidden',String(!active))});count.textContent=`${current+1} / ${images.length}`};const step=d=>{clearInterval(timer);show(current+d)};gallery.querySelector('[data-preview-previous]').onclick=e=>{e.stopPropagation();step(-1)};gallery.querySelector('[data-preview-next]').onclick=e=>{e.stopPropagation();step(1)};gallery.onpointerenter=()=>{if(fine.matches&&!reduced.matches){clearInterval(timer);timer=setInterval(()=>show(current+1),1250)}};gallery.onpointerleave=()=>clearInterval(timer);gallery.ontouchstart=e=>{touchStart=e.changedTouches[0].clientX};gallery.ontouchend=e=>{const d=e.changedTouches[0].clientX-touchStart;if(Math.abs(d)>42)step(d<0?1:-1)};show(0)});
  const quickView=main.querySelector('.product-quick-view'),stage=quickView.querySelector('.quick-view-stage'),stageImages=quickView.querySelector('.quick-view-images'),thumbs=quickView.querySelector('.quick-view-thumbs'),quickCount=quickView.querySelector('.quick-view-count');let quickIndex=0,returnFocus=null,quickTouchStart=0;
  const showQuickView=index=>{const total=stageImages.querySelectorAll('.sheet-view').length;quickIndex=(index+total)%total;stageImages.querySelectorAll('.sheet-view').forEach((img,i)=>{const active=i===quickIndex;img.classList.toggle('is-active',active);img.setAttribute('aria-hidden',String(!active))});thumbs.querySelectorAll('button').forEach((button,i)=>button.setAttribute('aria-current',String(i===quickIndex)));quickCount.textContent=`${quickIndex+1} / ${total}`};
  const openQuickView=(card,startAt=0)=>{
    const item=info.cards[Number(card.dataset.productIndex)],views=item.images||[0,1,2].map(view=>({card:item.asset,large:item.asset,view})),hasGallery=views.length>1,soldOut=item.availability==='Sold Out';
    returnFocus=card;stage.dataset.layout=item.layout;stage.dataset.row=item.row||0;stage.classList.toggle('single-view',!hasGallery);
    stageImages.innerHTML=views.map((image,i)=>`<img class="sheet-view ${item.images?'photo-view':`sheet-view-${image.view}`}" src="${image.large}" alt="${item.name}, view ${i+1} of ${views.length}" aria-hidden="${i!==startAt}">`).join('');
    thumbs.innerHTML=hasGallery?views.map((image,i)=>`<button type="button" aria-label="Show view ${i+1}" aria-current="${i===startAt}"><span class="quick-view-thumb product-sheet" data-layout="${item.layout}" data-row="${item.row||0}"><img class="sheet-view ${item.images?'photo-view':`sheet-view-${image.view}`} is-active" src="${image.card}" alt=""></span><span>0${i+1}</span></button>`).join(''):'';
    quickView.classList.toggle('is-sold-out',soldOut);quickView.querySelectorAll('.quick-view-arrow').forEach(button=>button.hidden=!hasGallery);quickCount.hidden=!hasGallery;thumbs.hidden=!hasGallery;
    quickView.querySelector('[data-quick-view-kicker]').textContent=item.images?`${info.title} · ${item.id}`:`${info.title} · Concept collection`;quickView.querySelector('#quick-view-title').textContent=item.name;quickView.querySelector('.quick-view-details').textContent=item.details;quickView.querySelector('.quick-view-price').textContent=item.price||'Contact us for price';
    quickView.querySelector('.quick-view-availability').textContent=soldOut?'Sold out':'Available';quickView.querySelector('[data-quick-view-action]').textContent=soldOut?'Enquire about similar sarees':'Enquire about this saree';
    quickView.querySelector('[data-quick-view-description]').textContent=item.images?(soldOut?'This piece has found its home. Browse every photograph, then contact us and we will help you find a similar Dhaniakhali saree.':hasGallery?'Use the gallery to explore the drape, border and woven detail of this saree.':'A closer view of the cloth, motif and woven detail.'):'Three considered views reveal the drape, border and woven detail. Final product photography, fiber specifications and measurements will be added before release.';
    quickView.querySelector('.quick-view-note').textContent=item.images?(soldOut?'Real product photography':'Real product photography · Available to enquire'):'Concept imagery · Price and availability to be confirmed';
    thumbs.querySelectorAll('button').forEach((button,i)=>button.onclick=()=>showQuickView(i));showQuickView(Math.min(startAt,views.length-1));quickView.showModal();document.body.classList.add('quick-view-open')
  };
  mastVisualElement.addEventListener('click',event=>{const link=event.target.closest('[data-feature-product]');if(!link)return;event.preventDefault();const index=info.cards.findIndex(item=>item.id===link.dataset.featureProduct),item=info.cards[index],card=main.querySelector(`[data-product-index="${index}"]`);if(index<0||!item||!card)return;applyFilter(item.type,{updateUrl:true});openQuickView(card)});
  const closeQuickView=()=>{quickView.close();document.body.classList.remove('quick-view-open');returnFocus?.focus()};
  cards.forEach(card=>{card.addEventListener('click',event=>{if(event.target.closest('.preview-arrows'))return;const active=[...card.querySelectorAll('.sheet-view')].findIndex(img=>img.classList.contains('is-active'));openQuickView(card,Math.max(active,0))});card.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();openQuickView(card)}})});
  quickView.querySelector('.quick-view-close').onclick=closeQuickView;quickView.querySelector('.quick-view-arrow.previous').onclick=()=>showQuickView(quickIndex-1);quickView.querySelector('.quick-view-arrow.next').onclick=()=>showQuickView(quickIndex+1);quickView.addEventListener('click',event=>{if(event.target===quickView)closeQuickView()});quickView.addEventListener('close',()=>document.body.classList.remove('quick-view-open'));stage.addEventListener('touchstart',event=>{quickTouchStart=event.changedTouches[0].clientX},{passive:true});stage.addEventListener('touchend',event=>{const distance=event.changedTouches[0].clientX-quickTouchStart;if(Math.abs(distance)>42)showQuickView(quickIndex+(distance<0?1:-1))},{passive:true});
  const scrollToSelection=()=>{const target=storySection.hidden?main.querySelector('#collection'):storySection;target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})};
  areaButtons.forEach(b=>b.onclick=()=>{applyFilter(b.dataset.area,{updateUrl:true});scrollToSelection()});typeLinks.forEach(l=>l.onclick=e=>{e.preventDefault();applyFilter(l.dataset.filter,{updateUrl:true});scrollToSelection()});const requestedFilter=location.hash.slice(1),initialFilter=requestedFilter||(info.types.length===1?info.types[0][1]:'all');applyFilter(initialFilter);if(requestedFilter)requestAnimationFrame(()=>requestAnimationFrame(scrollToSelection));addEventListener('hashchange',()=>{const filter=location.hash.slice(1)||(info.types.length===1?info.types[0][1]:'all');applyFilter(filter);if(location.hash)scrollToSelection()});
}
