const regionPages={
  bengal:{eyebrow:'West Bengal · Bangladesh',title:'Bengal Handloom',intro:'From weightless supplementary-weft muslin to narrative silk and crisp everyday cotton, Bengal’s looms speak in many distinct dialects.',board:'/assets/images/catalogue/regions/bengal-board.webp',groups:[['West Bengal','west-bengal'],['Bangladesh','bangladesh']],types:[['Gorod','gorod','west-bengal'],['Dhaniakhali','dhaniakhali','west-bengal'],['Baluchari','baluchari','west-bengal'],['Phulia','phulia','west-bengal'],['Bengal Kalakshetra','kalakshetra','west-bengal'],['Kantha','kantha','west-bengal'],['Dhakai Jamdani','jamdani','bangladesh'],['Tangail','tangail','bangladesh']],cards:[['Gorod','Silk · Red temple border','$315','#','gorod','west-bengal'],['Dhaniakhali','Cotton · Striped paar','$175','#','dhaniakhali','west-bengal'],['Baluchari','Silk · Narrative figured pallu','$485','/collections/baluchari.html','baluchari','west-bengal'],['Phulia','Cotton · Contemporary Bengal weave','$210','#','phulia','west-bengal'],['Bengal Kalakshetra','Cotton-silk · Art-led motifs','$265','#','kalakshetra','west-bengal'],['Kantha','Silk · Hand-stitched narrative','$340','#','kantha','west-bengal'],['Dhakai Jamdani','Fine cotton · Discontinuous extra weft','$325','/collections/jamdani.html','jamdani','bangladesh'],['Tangail','Cotton · Fine border and buti','$195','/collections/tangail.html','tangail','bangladesh']]},
  odisha:{eyebrow:'Odisha · Eastern India',title:'Odisha Handloom',intro:'Resist-dyed geometry, supplementary-weft storytelling and deeply rooted natural palettes distinguish Odisha’s celebrated weaving clusters.',board:'/assets/images/catalogue/regions/odisha-board.webp',types:[['Sambalpuri','sambalpuri'],['Bomkai','bomkai'],['Dhalapathar','dhalapathar'],['Kotpad','kotpad']],cards:[['Sambalpuri Bandha','Cotton · Double-sided ikat','$245','#','sambalpuri'],['Bomkai','Cotton-silk · Figured border','$285','#','bomkai'],['Dhalapathar','Cotton · Extra-weft geometry','$235','#','dhalapathar'],['Kotpad','Organic cotton · Natural madder','$225','#','kotpad']]},
  'south-india':{eyebrow:'Karnataka · Telangana',title:'South Indian Handloom',intro:'Graphic temple borders, ingenious joining techniques and cloth made for warm climates define these enduring southern traditions.',board:'/assets/images/catalogue/regions/south-india-board.webp',types:[['Ilkal','ilkal'],['Narayanpet','narayanpet'],['Patteda Anchu','patteda-anchu']],cards:[['Ilkal','Cotton · Tope teni border','$265','#','ilkal'],['Narayanpet','Cotton-silk · Temple border','$295','#','narayanpet'],['Patteda Anchu','Handspun cotton · Heritage border','$235','#','patteda-anchu']]},
  banarasi:{eyebrow:'Varanasi · Uttar Pradesh',title:'Banarasi',intro:'Lustrous silk, intricate zari and garden-like jaal patterns woven in one of India’s most storied textile cities.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:0,types:[['All Banarasi','all']],cards:[['Ruby Floral Jaal','Silk · Antique zari','$625','#','all'],['Meenakari Butidar','Silk · Multicolour supplementary weft','$695','#','all'],['Tissue Kadhwa','Silk tissue · Kadhwa motifs','$745','#','all']]},
  kanchipuram:{eyebrow:'Kanchipuram · Tamil Nadu',title:'Kanchipuram',intro:'Architectural borders, substantial silk and the celebrated korvai join give Kanchipuram sarees their unmistakable presence.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:1,types:[['All Kanchipuram','all']],cards:[['Peacock Korvai','Mulberry silk · Contrast border','$720','#','all'],['Temple Rekku','Mulberry silk · Zari','$785','#','all'],['Checks & Mayil','Mulberry silk · Figured pallu','$815','#','all']]},
  maheshwari:{eyebrow:'Maheshwar · Madhya Pradesh',title:'Maheshwari',intro:'Light silk-cotton, elegant stripes and reversible borders carry the refined geometry of Maheshwar’s weaving heritage.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:2,types:[['All Maheshwari','all']],cards:[['Sage Chandrakala','Silk-cotton · Zari border','$285','#','all'],['Baingani Leher','Silk-cotton · Striped pallu','$310','#','all'],['Narmada Checks','Silk-cotton · Reversible border','$325','#','all']]}
};
const key=document.body.dataset.region,info=regionPages[key],main=document.querySelector('#main-content');
if(info&&main){
  const panelStyle=info.panel==null?'':`style="width:300%;max-width:none;transform:translateX(-${info.panel*33.333}%);object-fit:cover"`;
  const areaFilters=info.groups?`<div class="filter-level" data-area-filters><p>1 · Choose an area</p><div><button data-area="all" aria-pressed="true">All Bengal</button>${info.groups.map(([name,slug])=>`<button data-area="${slug}" aria-pressed="false">${name}</button>`).join('')}</div></div>`:'';
  const typeFilters=`<div class="filter-level" data-type-filters><p>${info.groups?'2 · Choose a weave':'Filter by weave'}</p><div><a href="#all" data-filter="all" data-area="all">All ${info.title.replace(' Handloom','')}</a>${info.types.filter(([,slug])=>slug!=='all').map(([name,slug,area])=>`<a id="filter-${slug}" href="#${slug}" data-filter="${slug}" data-area="${area||'all'}">${name}</a>`).join('')}</div></div>`;
  main.innerHTML=`<section class="region-mast"><div><p class="eyebrow">${info.eyebrow}</p><h1>${info.title}</h1><p>${info.intro}</p></div><div class="region-board"><img ${panelStyle} src="${info.board}" alt="AI-created collection preview of ${info.title} sarees"></div></section><section class="collection-filters" aria-label="Filter ${info.title} collection"><div class="filter-heading"><p class="eyebrow">Refine the collection</p><h2>Find your weave</h2><p data-filter-summary aria-live="polite"></p></div>${areaFilters}${typeFilters}</section><section class="preview-section" id="collection"><div class="preview-head"><div><p class="eyebrow">Collection preview</p><h2 data-results-title>All ${info.title}</h2></div><p class="demo-note">Concept imagery · Final prices coming soon</p></div><div class="preview-grid">${info.cards.map((c,i)=>`<a class="preview-card" data-panel="${info.panel==null?i%3:info.panel}" data-type="${c[4]}" data-area="${c[5]||'all'}" href="${c[3]}"><div class="preview-image"><img src="${info.board}" alt="${c[0]} saree preview"><span class="preview-badge">Preview</span></div><h3>${c[0]}</h3><p>${c[1]} · XX$</p></a>`).join('')}</div></section>`;
  const cards=[...main.querySelectorAll('.preview-card')],typeLinks=[...main.querySelectorAll('[data-filter]')],areaButtons=[...main.querySelectorAll('[data-area-filters] button')],summary=main.querySelector('[data-filter-summary]'),resultsTitle=main.querySelector('[data-results-title]');let selectedArea='all';
  const labelFor=slug=>info.types.find(([,value])=>value===slug)?.[0]||info.groups?.find(([,value])=>value===slug)?.[0]||`All ${info.title}`;
  function applyFilter(value,{updateUrl=false}={}){const typeExists=info.types.some(([,slug])=>slug===value),areaExists=info.groups?.some(([,slug])=>slug===value),selectedType=typeExists?value:'all';if(areaExists)selectedArea=value;else if(typeExists&&value!=='all')selectedArea=info.types.find(([,slug])=>slug===value)?.[2]||'all';else selectedArea='all';areaButtons.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.area===selectedArea)));typeLinks.forEach(link=>{const belongs=selectedArea==='all'||link.dataset.area==='all'||link.dataset.area===selectedArea;link.hidden=!belongs;link.classList.toggle('is-active',selectedType===link.dataset.filter||(selectedType==='all'&&link.dataset.filter==='all'));link.setAttribute('aria-current',link.classList.contains('is-active')?'true':'false')});let count=0;cards.forEach(card=>{const show=selectedType!=='all'?card.dataset.type===selectedType:selectedArea==='all'||card.dataset.area===selectedArea;card.hidden=!show;if(show)count++});const chosen=selectedType!=='all'?labelFor(selectedType):selectedArea!=='all'?labelFor(selectedArea):`All ${info.title}`;resultsTitle.textContent=chosen;summary.textContent=`Showing ${count} ${count===1?'saree':'sarees'} · ${chosen}`;if(updateUrl)history.replaceState(null,'',value==='all'?location.pathname:`#${value}`)}
  areaButtons.forEach(button=>button.addEventListener('click',()=>applyFilter(button.dataset.area,{updateUrl:true})));typeLinks.forEach(link=>link.addEventListener('click',event=>{event.preventDefault();applyFilter(link.dataset.filter,{updateUrl:true});main.querySelector('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}));applyFilter(location.hash.slice(1)||'all');addEventListener('hashchange',()=>applyFilter(location.hash.slice(1)||'all'));
}
