const product=(name,details,type,area,asset,row=0,layout='grid')=>({name,details,type,area,asset,row,layout});
const paired=(asset,type,area,a,b)=>[product(a[0],a[1],type,area,asset,0),product(b[0],b[1],type,area,asset,1)];
const P='/assets/images/products/';
const dhaniakhaliProduct=(id,name,design,colors,count,price=45)=>({
  id,name,design,colors,type:'dhaniakhali',area:'all',layout:'photos',price:`$${price}`,priceValue:price,
  details:`Pure cotton · ${colors.join(', ')} · GI-tagged Dhaniakhali weave`,
  images:Array.from({length:count},(_,index)=>{
    const number=String(index+1).padStart(2,'0');
    return {card:`${P}dhaniakhali/${id}/${number}-card.jpg`,large:`${P}dhaniakhali/${id}/${number}-large.jpg`};
  })
});
const regionPages={
  bengal:{eyebrow:'Eastern India · Living handloom traditions',title:'Bengal Handloom',intro:'From crisp everyday cotton to narrative silk, Bengal’s looms speak through distinctive borders, texture and enduring regional craft.',board:'/assets/images/catalogue/regions/bengal-board.webp',types:[['Gorod','gorod'],['Dhaniakhali','dhaniakhali'],['Baluchari','baluchari'],['Phulia','phulia'],['Bengal Kalakshetra','kalakshetra']],cards:[
    ...paired(P+'gorod-products.webp','gorod','all',['Shankha Ivory Gorod','Silk · Red temple border'],['Sindoor Cream Gorod','Silk · Fine red paar']),
    dhaniakhaliProduct('DHA-001','Fish Motif Dhaniakhali','Fish Motif',['White','Red'],1),
    dhaniakhaliProduct('DHA-002','Fish Motif Dhaniakhali','Fish Motif',['White','Red','Black'],1),
    dhaniakhaliProduct('DHA-003','Fish Motif Dhaniakhali','Fish Motif',['White','Red','Basanti Yellow'],1),
    dhaniakhaliProduct('DHA-004','Fish Motif Dhaniakhali','Fish Motif',['White','Red','Yellow'],1),
    dhaniakhaliProduct('DHA-005','Ikat Border Dhaniakhali','Ikat Border',['White','Red'],2),
    dhaniakhaliProduct('DHA-006','Traditional Dhaniakhali','Traditional',['White','Red'],3),
    dhaniakhaliProduct('DHA-007','Traditional Dhaniakhali','Traditional',['White','Red','Black'],2),
    dhaniakhaliProduct('DHA-008','Traditional Dhaniakhali','Traditional',['Light Pink','Pinkish Red'],2),
    dhaniakhaliProduct('DHA-009','Traditional Dhaniakhali','Traditional',['Light Pink','Rose Red'],3),
    product('Ranga Oxblood Baluchari','Silk · Narrative figured pallu','baluchari','all',P+'baluchari-oxblood-views.webp',0,'strip'),product('Bonolata Olive Baluchari','Silk · Figured floral pallu','baluchari','all',P+'baluchari-olive-views.webp',0,'strip'),
    ...paired(P+'phulia-products.webp','phulia','all',['Sage Rekha Phulia','Cotton · Contemporary border'],['Megh Blue Phulia','Cotton · Fine buti']),
    ...paired(P+'kalakshetra-products.webp','kalakshetra','all',['Terracotta Lok Kalakshetra','Cotton-silk · Folk motifs'],['Indigo Bagan Kalakshetra','Cotton-silk · Botanical motifs'])]},
  odisha:{eyebrow:'Odisha · Eastern India',title:'Odisha Handloom',intro:'A focused presentation of Dhalapathar’s rooted cotton tradition and distinctive extra-weft geometry.',board:'/assets/images/catalogue/regions/odisha-board.webp',types:[['Dhalapathar','dhalapathar']],cards:[
    ...paired(P+'dhalapathar-products.webp','dhalapathar','all',['Mati Rekha Dhalapathar','Cotton · Extra-weft geometry'],['Neel Rekha Dhalapathar','Cotton · Graphic border'])]},
  'south-india':{eyebrow:'Karnataka · Telangana',title:'South Indian Handloom',intro:'Graphic temple borders, ingenious joining techniques and cloth made for warm climates define these enduring southern traditions.',board:'/assets/images/catalogue/regions/south-india-board.webp',types:[['Ilkal','ilkal'],['Narayanpet','narayanpet'],['Patteda Anchu','patteda-anchu']],cards:[
    ...paired(P+'ilkal-products.webp','ilkal','all',['Rakta Tope Teni Ilkal','Cotton-silk · Tope teni border'],['Neel Maroon Ilkal','Cotton-silk · Contrast pallu']),...paired(P+'narayanpet-products.webp','narayanpet','all',['Haldi Temple Narayanpet','Cotton-silk · Temple border'],['Teal Checks Narayanpet','Cotton-silk · Fine checks']),...paired(P+'patteda-anchu-products.webp','patteda-anchu','all',['Kora Anchu Patteda','Handspun cotton · Heritage border'],['Charcoal Anchu Patteda','Handspun cotton · Narrow stripe'])]},
  banarasi:{eyebrow:'Varanasi · Uttar Pradesh',title:'Banarasi',intro:'Lustrous silk, intricate zari and garden-like jaal patterns woven in one of India’s most storied textile cities.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:0,types:[['Banarasi','banarasi']],cards:paired(P+'banarasi-products.webp','banarasi','all',['Ruby Floral Jaal','Silk · Antique zari'],['Teal Meenakari Butidar','Silk · Multicolour supplementary weft'])},
  kanchipuram:{eyebrow:'Kanchipuram · Tamil Nadu',title:'Kanchipuram',intro:'Architectural borders, substantial silk and the celebrated korvai join give Kanchipuram sarees their unmistakable presence.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:1,types:[['Kanchipuram','kanchipuram']],cards:paired(P+'kanchipuram-products.webp','kanchipuram','all',['Maroon Temple Korvai','Mulberry silk · Contrast border'],['Peacock Magenta Korvai','Mulberry silk · Figured pallu'])},
  maheshwari:{eyebrow:'Maheshwar · Madhya Pradesh',title:'Maheshwari',intro:'Light silk-cotton, elegant stripes and reversible borders carry the refined geometry of Maheshwar’s weaving heritage.',board:'/assets/images/catalogue/regions/silk-regions-board.webp',panel:2,types:[['Maheshwari','maheshwari']],cards:paired(P+'maheshwari-products.webp','maheshwari','all',['Sage Chandrakala','Silk-cotton · Zari border'],['Baingani Checks','Silk-cotton · Reversible border'])}
};
const categoryStories={
  bengal:{
    dhaniakhali:{kicker:'Hooghly district · West Bengal',title:'The quiet rhythm of Bengal cotton',lead:'Crisp, enduring and unmistakably grounded in place.',facts:[['Cloth','Handloom cotton'],['Known for','Distinctive woven borders'],['Heritage','Geographical Indication protected']],paragraphs:[
      'Dhaniakhali is a traditional cotton handloom saree from the Hooghly district of West Bengal, with a weaving heritage that stretches back generations. Known for its crisp cotton, distinctive borders, and everyday elegance, the saree developed around the weaving communities of Dhaniakhali and the surrounding villages.',
      'Originally valued as a practical cotton saree for Bengal’s warm climate, Dhaniakhali became known for its durability, comfort, and understated beauty. Traditionally woven on handlooms, its character comes from the slight texture of the cloth and the rhythm of the woven border rather than elaborate ornamentation.',
      'Today, Dhaniakhali remains part of Bengal’s living handloom tradition and is protected by a Geographical Indication (GI) tag, recognizing its connection to the region and its weaving heritage.'
    ]}
  }
};
const editorial=(kicker,title,lead,facts,paragraphs)=>({kicker,title,lead,facts,paragraphs});
Object.assign(categoryStories.bengal,{
  gorod:editorial('Murshidabad · West Bengal','Ivory silk, edged in red','Ceremonial restraint expressed through cloth.',[['Cloth','Silk'],['Signature','Red border on an ivory body'],['Character','Light, luminous, understated']],['Gorod is recognized for an ivory or undyed silk ground framed by a red border. Its beauty lies in restraint: the natural glow of silk, a decisive paar and a composition that allows the cloth itself to remain central.','Closely associated with Bengal’s ceremonial wardrobe, Gorod is often chosen for religious and festive occasions. Handloom texture keeps the surface alive, giving an apparently simple saree quiet depth.']),
  baluchari:editorial('Bishnupur · West Bengal','A pallu that tells a story','Silk becomes a woven picture gallery.',[['Cloth','Figured silk'],['Signature','Narrative pallu panels'],['Heritage','Geographical Indication protected']],['Baluchari sarees are celebrated for elaborate pallus woven with figurative scenes, floral frames and architectural borders. Rather than relying on embroidery, their imagery is constructed within the weave.','The tradition is strongly associated with Bishnupur. Each composition rewards close looking: borders establish the frame while the pallu carries the saree’s central narrative.']),
  phulia:editorial('Nadia district · West Bengal','Tradition in a lighter register','Fine cotton shaped by a contemporary weaving centre.',[['Cloth','Fine handloom cotton'],['Place','Phulia and the Nadia weaving belt'],['Character','Light, precise, versatile']],['Phulia is an important handloom centre in Nadia district, known for fine cotton sarees that balance inherited Bengal techniques with evolving design. Crisp borders, restrained motifs and breathable cloth give the weave its everyday versatility.','The saree’s identity comes from the intelligence of proportion: body, border and pallu are composed to feel light without becoming visually slight.']),
  kalakshetra:editorial('Bengal · Art-led handloom','The loom as a drawing surface','Folk memory and graphic rhythm meet in cloth.',[['Cloth','Cotton or cotton-silk'],['Signature','Art-led figurative motifs'],['Character','Graphic, narrative, expressive']],['Bengal Kalakshetra sarees bring an art-led sensibility to regional handloom, using woven or textile-applied motifs inspired by folk imagery, landscape and everyday cultural memory.','The emphasis is expressive rather than uniform. Borders and pallus become fields for drawing with thread, allowing each saree to carry a distinct visual voice.'])
});
categoryStories.odisha={dhalapathar:editorial('Khurda district · Odisha','Geometry with a village memory','A distinctive cotton tradition rooted in Dhalapathar.',[['Cloth','Handloom cotton'],['Signature','Extra-warp and extra-weft patterning'],['Heritage','Geographical Indication protected']],['Dhalapathar is associated with a weaving community in Odisha’s Khurda district. Its textile vocabulary is known for strong geometric arrangement and pattern created through carefully controlled supplementary threads.','The tradition extends beyond sarees to furnishing textiles, yet the same disciplined construction remains visible: a sturdy cotton ground animated by borders, bands and culturally rooted motifs.'])};
categoryStories['south-india']={
  ilkal:editorial('Karnataka','A border joined with ingenuity','Bold colour and the distinctive tope teni construction.',[['Cloth','Cotton body with silk or art-silk pallu'],['Signature','Tope teni joining technique'],['Heritage','Geographical Indication protected']],['Ilkal sarees are distinguished by the structural relationship between body, border and pallu. The celebrated tope teni technique joins separately prepared warps, creating a decisive transition in colour and material.','Graphic stripes and temple-like forms give the pallu a strong cadence, while the cotton body keeps the saree practical and wearable.']),
  narayanpet:editorial('Telangana','Checks, stripes and temple edges','A compact southern classic made for movement.',[['Cloth','Cotton or silk-cotton'],['Signature','Checked body and temple border'],['Character','Light, graphic, practical']],['Narayanpet sarees are known for checked or striped fields, contrast borders and small temple-inspired forms. Their structure is clear and rhythmic, making them easy to recognize without elaborate surface ornament.','Traditionally valued for comfort and durability, the weave brings together an everyday lightness and a distinctly southern graphic language.']),
  'patteda-anchu':editorial('Karnataka','A narrow border, precisely placed','Handloom cotton with an austere, enduring beauty.',[['Cloth','Handloom cotton'],['Signature','Narrow anchu border'],['Character','Minimal, breathable, grounded']],['Patteda Anchu is a Karnataka cotton saree tradition recognized by its narrow border and direct, functional beauty. The cloth is breathable and the composition intentionally spare.','Its appeal comes from proportion and texture rather than excess decoration—a reminder that handloom character can be most powerful when the design is reduced to its essentials.'])
};
categoryStories.banarasi={banarasi:editorial('Varanasi · Uttar Pradesh','A garden drawn in silk and zari','Lustre, density and extraordinary brocade skill.',[['Cloth','Silk brocade'],['Signature','Zari, jaal and butidar patterning'],['Heritage','Geographical Indication protected']],['Banarasi sarees are woven in and around Varanasi and are celebrated for richly structured brocade. Floral jaals, individual butis and metallic zari are organized through techniques that can range from delicate to architectural.','The finest examples reveal their complexity gradually: first as lustre and pattern, then as a close conversation between ground cloth, supplementary threads and the disciplined hand of the weaver.'])};
categoryStories.kanchipuram={kanchipuram:editorial('Tamil Nadu','Silk with architectural presence','Temple geometry, saturated colour and the strength of korvai.',[['Cloth','Mulberry silk'],['Signature','Contrast korvai border'],['Heritage','Geographical Indication protected']],['Kanchipuram sarees are known for substantial silk, saturated colour and borders that often echo the geometry of temple architecture. In korvai construction, contrasting sections are joined with exceptional control.','The result is both visual and structural: a saree with weight, clarity and a pallu designed to hold its presence across generations.'])};
categoryStories.maheshwari={maheshwari:editorial('Maheshwar · Madhya Pradesh','Lightness framed by geometry','Reversible borders and an elegant silk-cotton balance.',[['Cloth','Silk-cotton'],['Signature','Reversible border and striped pallu'],['Character','Light, polished, architectural']],['Maheshwari sarees are associated with the weaving town of Maheshwar and are valued for their light silk-cotton body, fine stripes, checks and elegantly controlled borders.','Many examples use a reversible border, giving both sides a finished appearance. The weave feels refined without heaviness, carrying the measured geometry of its place of origin.'])};
const key=document.body.dataset.region,info=regionPages[key],main=document.querySelector('#main-content');
if(info&&main){
  const panelStyle=info.panel==null?'':`style="width:300%;max-width:none;transform:translateX(-${info.panel*33.333}%);object-fit:cover"`;
  const bengalFeatures=[['DHA-003','Fish Motif','/assets/images/products/dhaniakhali/DHA-003/01-card.jpg'],['DHA-005','Ikat Border','/assets/images/products/dhaniakhali/DHA-005/01-card.jpg'],['DHA-007','Traditional','/assets/images/products/dhaniakhali/DHA-007/01-card.jpg']];
  const mastVisual=key==='bengal'?`<div class="region-board bengal-feature-board" aria-label="Featured Dhaniakhali sarees">${bengalFeatures.map(([id,design,image])=>`<a href="#dhaniakhali" data-feature-product="${id}" aria-label="View ${design} Dhaniakhali, ${id}"><img src="${image}" alt="${design} Dhaniakhali saree"><span><small>Dhaniakhali</small>${design}</span></a>`).join('')}</div>`:`<div class="region-board region-coming-board" aria-label="${info.title} collection in preparation"><span class="loom-line line-one"></span><span class="loom-line line-two"></span><div><p>In preparation</p><strong>New pieces,<br>thoughtfully chosen.</strong><small>Real product photography will arrive with the collection.</small></div></div>`;
  const areaFilters=info.groups?`<div class="filter-level" data-area-filters><p>1 · Choose an area</p><div><button data-area="all" aria-pressed="true">All Bengal</button>${info.groups.map(([name,slug])=>`<button data-area="${slug}" aria-pressed="false">${name}</button>`).join('')}</div></div>`:'';
  const typeFilters=`<div class="filter-level" data-type-filters><p>${info.groups?'2 · Choose a weave':'Filter by weave'}</p><div><a href="#all" data-filter="all" data-area="all">All ${info.title.replace(' Handloom','')}</a>${info.types.filter(([,slug])=>slug!=='all').map(([name,slug,area])=>`<a id="filter-${slug}" href="#${slug}" data-filter="${slug}" data-area="${area||'all'}">${name}</a>`).join('')}</div></div>`;
  const dhaniakhali=info.cards.filter(card=>card.type==='dhaniakhali'&&card.images),designs=[...new Set(dhaniakhali.map(card=>card.design))],colors=[...new Set(dhaniakhali.flatMap(card=>card.colors))],prices=dhaniakhali.map(card=>card.priceValue),minPrice=prices.length?Math.min(...prices):0,maxPrice=prices.length?Math.max(...prices):0;
  const facetMarkup=dhaniakhali.length?`<aside class="product-facets" data-product-facets hidden aria-label="Filter Dhaniakhali products"><div class="facet-intro"><div><p class="eyebrow">Refine Dhaniakhali</p><h3>Find your saree</h3></div><button type="button" data-clear-facets>Clear filters</button></div><fieldset><legend>Design</legend><div class="facet-options"><button type="button" data-facet="design" data-value="all" aria-pressed="true">All designs</button>${designs.map(value=>`<button type="button" data-facet="design" data-value="${value}" aria-pressed="false">${value}</button>`).join('')}</div></fieldset><fieldset><legend>Color</legend><div class="facet-options"><button type="button" data-facet="color" data-value="all" aria-pressed="true">All colors</button>${colors.map(value=>`<button type="button" data-facet="color" data-value="${value}" aria-pressed="false"><span class="color-dot" data-color="${value.toLowerCase().replaceAll(' ','-')}"></span>${value}</button>`).join('')}</div></fieldset><fieldset class="price-facet"><legend>Price</legend><div><label for="maximum-price">Up to <output data-price-output>$${maxPrice}</output></label><input id="maximum-price" data-price-range type="range" min="${minPrice}" max="${maxPrice}" value="${maxPrice}" step="1" ${minPrice===maxPrice?'disabled':''}><span>${minPrice===maxPrice?`All current pieces are $${minPrice}`:`$${minPrice}–$${maxPrice}`}</span></div></fieldset><p class="facet-results" data-facet-results aria-live="polite"></p></aside>`:'';
  const comingMarkup=`<div class="collection-coming-soon" data-coming-soon hidden><p class="eyebrow">Collection in preparation</p><h3>Something beautiful is on its way.</h3><p>We are thoughtfully assembling this collection and photographing every piece. Please stay tuned for the first release.</p><a href="/index.html#contact">Join the first look <span aria-hidden="true">↗</span></a></div>`;
  const cardMarkup=info.cards.map((c,index)=>{
    if(!c.images)return '';
    const views=c.images||[0,1,2].map(view=>({card:c.asset,view})),hasGallery=views.length>1;
    const images=views.map((image,i)=>`<img class="sheet-view ${c.images?'photo-view':`sheet-view-${image.view}`}${i===0?' is-active':''}" src="${image.card}" alt="${i===0?`${c.name} product photograph`:''}" aria-hidden="${i!==0}" loading="lazy">`).join('');
    return `<article class="preview-card${c.images?' real-product':''}" data-product-index="${index}" data-type="${c.type}" data-area="${c.area}" data-design="${c.design||''}" data-colors="${c.colors?.join('|')||''}" data-price="${c.priceValue||''}" tabindex="0" aria-label="Open ${c.name} details"><div class="preview-image product-sheet" data-layout="${c.layout}" data-row="${c.row||0}">${images}<span class="preview-badge">${c.id||'Concept'}</span>${hasGallery?`<div class="preview-arrows"><button type="button" data-preview-previous aria-label="Previous view">‹</button><button type="button" data-preview-next aria-label="Next view">›</button></div><span class="preview-count" aria-hidden="true">1 / ${views.length}</span>`:''}</div><h3>${c.name}</h3><p>${c.details} · <strong>${c.price||'XX$'}</strong></p><span class="preview-open">View details <span aria-hidden="true">↗</span></span></article>`;
  }).join('');
  main.innerHTML=`<section class="region-mast"><div><p class="eyebrow">${info.eyebrow}</p><h1>${info.title}</h1><p>${info.intro}</p></div>${mastVisual}</section><section class="collection-filters"><div class="filter-heading"><p class="eyebrow">Refine the collection</p><h2>Find your weave</h2><p data-filter-summary aria-live="polite"></p></div>${areaFilters}${typeFilters}</section><section class="category-story" data-category-story hidden></section><section class="preview-section" id="collection"><div class="preview-head"><div><p class="eyebrow">Collection preview</p><h2 data-results-title>All ${info.title}</h2></div><p class="demo-note" data-collection-note>Concept imagery · Final prices coming soon</p></div>${facetMarkup}${comingMarkup}<div class="preview-grid">${cardMarkup}</div></section><dialog class="product-quick-view" aria-labelledby="quick-view-title"><button class="quick-view-close" type="button" aria-label="Close product details">×</button><div class="quick-view-layout"><div class="quick-view-media"><div class="quick-view-stage product-sheet"><div class="quick-view-images"></div><button class="quick-view-arrow previous" type="button" aria-label="Previous product view">‹</button><button class="quick-view-arrow next" type="button" aria-label="Next product view">›</button><span class="quick-view-count" aria-live="polite"></span></div><div class="quick-view-thumbs" aria-label="Choose a product view"></div></div><div class="quick-view-copy"><p class="eyebrow" data-quick-view-kicker></p><h2 id="quick-view-title"></h2><p class="quick-view-details"></p><p class="quick-view-price"></p><div class="quick-view-rule"></div><p data-quick-view-description></p><a class="button primary" href="/index.html#contact">Enquire about this saree <span>↘</span></a><p class="quick-view-note"></p></div></div></dialog>`;
  const cards=[...main.querySelectorAll('.preview-card')],typeLinks=[...main.querySelectorAll('[data-filter]')],areaButtons=[...main.querySelectorAll('[data-area-filters] button')],summary=main.querySelector('[data-filter-summary]'),resultsTitle=main.querySelector('[data-results-title]'),storySection=main.querySelector('[data-category-story]'),facets=main.querySelector('[data-product-facets]'),comingSoon=main.querySelector('[data-coming-soon]');let selectedArea='all',selectedType='all',selectedDesign='all',selectedColor='all',selectedMax=maxPrice;
  main.querySelector('[data-collection-note]').textContent=key==='bengal'?'Real Dhaniakhali photography · More collections arriving soon':'New collection in preparation';
  const labelFor=slug=>info.types.find(([,v])=>v===slug)?.[0]||info.groups?.find(([,v])=>v===slug)?.[0]||`All ${info.title}`;
  const renderCategoryStory=slug=>{const story=categoryStories[key]?.[slug];if(!story){storySection.hidden=true;storySection.innerHTML='';return}storySection.innerHTML=`<div class="category-story-heading"><p class="eyebrow">${story.kicker}</p><h2>${labelFor(slug)}</h2><h3>${story.title}</h3><p class="category-story-lead">${story.lead}</p></div><div class="category-story-body">${story.paragraphs.map((paragraph,index)=>`<p${index===0?' class="drop-cap"':''}>${paragraph}</p>`).join('')}</div><dl class="category-story-facts">${story.facts.map(([term,value])=>`<div><dt>${term}</dt><dd>${value}</dd></div>`).join('')}</dl><div class="category-story-action"><a class="category-story-jump" href="#collection">View the collection <span aria-hidden="true">↓</span></a></div><span class="category-story-mark" aria-hidden="true">ধ</span>`;storySection.hidden=false;storySection.querySelector('.category-story-jump').onclick=event=>{event.preventDefault();main.querySelector('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}};
  const applyProductFacets=()=>{if(!facets||selectedType!=='dhaniakhali')return;let count=0;cards.filter(card=>card.dataset.type==='dhaniakhali').forEach(card=>{const designMatch=selectedDesign==='all'||card.dataset.design===selectedDesign,colorMatch=selectedColor==='all'||card.dataset.colors.split('|').includes(selectedColor),priceMatch=Number(card.dataset.price)<=selectedMax,show=designMatch&&colorMatch&&priceMatch;card.hidden=!show;if(show)count++});facets.querySelector('[data-facet-results]').textContent=`${count} of ${dhaniakhali.length} ${count===1?'saree':'sarees'}`;summary.textContent=`Showing ${count} ${count===1?'saree':'sarees'} · Dhaniakhali`};
  const resetProductFacets=()=>{selectedDesign='all';selectedColor='all';selectedMax=maxPrice;if(!facets)return;facets.querySelectorAll('[data-facet]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.value==='all')));const range=facets.querySelector('[data-price-range]');range.value=maxPrice;facets.querySelector('[data-price-output]').textContent=`$${maxPrice}`;applyProductFacets()};
  function applyFilter(value,{updateUrl=false}={}){const typeExists=info.types.some(([,s])=>s===value),areaExists=info.groups?.some(([,s])=>s===value);selectedType=typeExists?value:'all';if(areaExists)selectedArea=value;else if(typeExists&&value!=='all')selectedArea=info.types.find(([,s])=>s===value)?.[2]||'all';else selectedArea='all';areaButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.area===selectedArea)));typeLinks.forEach(l=>{const belongs=selectedArea==='all'||l.dataset.area==='all'||l.dataset.area===selectedArea;l.hidden=!belongs;l.classList.toggle('is-active',selectedType===l.dataset.filter||(selectedType==='all'&&l.dataset.filter==='all'));l.setAttribute('aria-current',l.classList.contains('is-active')?'true':'false')});let count=0;cards.forEach(c=>{const show=selectedType!=='all'?c.dataset.type===selectedType:selectedArea==='all'||c.dataset.area===selectedArea;c.hidden=!show;if(show)count++});if(facets){facets.hidden=selectedType!=='dhaniakhali';if(selectedType==='dhaniakhali')applyProductFacets()}const chosen=selectedType!=='all'?labelFor(selectedType):selectedArea!=='all'?labelFor(selectedArea):`All ${info.title}`;resultsTitle.textContent=chosen;comingSoon.hidden=count>0;if(selectedType!=='dhaniakhali')summary.textContent=count?`Showing ${count} ${count===1?'saree':'sarees'} · ${chosen}`:`Collection in preparation · ${chosen}`;renderCategoryStory(selectedType);if(updateUrl)history.replaceState(null,'',value==='all'?location.pathname:`#${value}`)}
  if(facets){facets.querySelectorAll('[data-facet]').forEach(button=>button.onclick=()=>{const facet=button.dataset.facet,value=button.dataset.value;if(facet==='design')selectedDesign=value;else selectedColor=value;facets.querySelectorAll(`[data-facet="${facet}"]`).forEach(option=>option.setAttribute('aria-pressed',String(option===button)));applyProductFacets()});const range=facets.querySelector('[data-price-range]');range.oninput=()=>{selectedMax=Number(range.value);facets.querySelector('[data-price-output]').textContent=`$${selectedMax}`;applyProductFacets()};facets.querySelector('[data-clear-facets]').onclick=resetProductFacets}
  cards.forEach(card=>{const gallery=card.querySelector('.preview-image'),images=[...gallery.querySelectorAll('.sheet-view')],count=gallery.querySelector('.preview-count'),fine=matchMedia('(hover: hover) and (pointer: fine)'),reduced=matchMedia('(prefers-reduced-motion: reduce)');if(images.length<2)return;let current=0,timer,touchStart=0;const show=index=>{current=(index+images.length)%images.length;images.forEach((img,i)=>{const active=i===current;img.classList.toggle('is-active',active);img.setAttribute('aria-hidden',String(!active))});count.textContent=`${current+1} / ${images.length}`};const step=d=>{clearInterval(timer);show(current+d)};gallery.querySelector('[data-preview-previous]').onclick=e=>{e.stopPropagation();step(-1)};gallery.querySelector('[data-preview-next]').onclick=e=>{e.stopPropagation();step(1)};gallery.onpointerenter=()=>{if(fine.matches&&!reduced.matches){clearInterval(timer);timer=setInterval(()=>show(current+1),1250)}};gallery.onpointerleave=()=>clearInterval(timer);gallery.ontouchstart=e=>{touchStart=e.changedTouches[0].clientX};gallery.ontouchend=e=>{const d=e.changedTouches[0].clientX-touchStart;if(Math.abs(d)>42)step(d<0?1:-1)};show(0)});
  const quickView=main.querySelector('.product-quick-view'),stage=quickView.querySelector('.quick-view-stage'),stageImages=quickView.querySelector('.quick-view-images'),thumbs=quickView.querySelector('.quick-view-thumbs'),quickCount=quickView.querySelector('.quick-view-count');let quickIndex=0,returnFocus=null,quickTouchStart=0;
  const showQuickView=index=>{const total=stageImages.querySelectorAll('.sheet-view').length;quickIndex=(index+total)%total;stageImages.querySelectorAll('.sheet-view').forEach((img,i)=>{const active=i===quickIndex;img.classList.toggle('is-active',active);img.setAttribute('aria-hidden',String(!active))});thumbs.querySelectorAll('button').forEach((button,i)=>button.setAttribute('aria-current',String(i===quickIndex)));quickCount.textContent=`${quickIndex+1} / ${total}`};
  const openQuickView=(card,startAt=0)=>{const item=info.cards[Number(card.dataset.productIndex)],views=item.images||[0,1,2].map(view=>({card:item.asset,large:item.asset,view})),hasGallery=views.length>1;returnFocus=card;stage.dataset.layout=item.layout;stage.dataset.row=item.row||0;stage.classList.toggle('single-view',!hasGallery);stageImages.innerHTML=views.map((image,i)=>`<img class="sheet-view ${item.images?'photo-view':`sheet-view-${image.view}`}" src="${image.large}" alt="${item.name}, view ${i+1} of ${views.length}" aria-hidden="${i!==startAt}">`).join('');thumbs.innerHTML=hasGallery?views.map((image,i)=>`<button type="button" aria-label="Show view ${i+1}" aria-current="${i===startAt}"><span class="quick-view-thumb product-sheet" data-layout="${item.layout}" data-row="${item.row||0}"><img class="sheet-view ${item.images?'photo-view':`sheet-view-${image.view}`} is-active" src="${image.card}" alt=""></span><span>0${i+1}</span></button>`).join(''):'';quickView.querySelectorAll('.quick-view-arrow').forEach(button=>button.hidden=!hasGallery);quickCount.hidden=!hasGallery;thumbs.hidden=!hasGallery;quickView.querySelector('[data-quick-view-kicker]').textContent=item.images?`${info.title} · ${item.id}`:`${info.title} · Concept collection`;quickView.querySelector('#quick-view-title').textContent=item.name;quickView.querySelector('.quick-view-details').textContent=item.details;quickView.querySelector('.quick-view-price').textContent=item.price||'XX$';quickView.querySelector('[data-quick-view-description]').textContent=item.images?(hasGallery?'Use the gallery to explore the drape, border and woven detail of this saree.':'A closer view of the cloth, motif and woven detail.'):'Three considered views reveal the drape, border and woven detail. Final product photography, fiber specifications and measurements will be added before release.';quickView.querySelector('.quick-view-note').textContent=item.images?'Real product photography · Available to enquire':'Concept imagery · Price and availability to be confirmed';thumbs.querySelectorAll('button').forEach((button,i)=>button.onclick=()=>showQuickView(i));showQuickView(Math.min(startAt,views.length-1));quickView.showModal();document.body.classList.add('quick-view-open')};
  main.querySelectorAll('[data-feature-product]').forEach(link=>link.onclick=event=>{event.preventDefault();const index=info.cards.findIndex(item=>item.id===link.dataset.featureProduct);if(index<0)return;applyFilter('dhaniakhali',{updateUrl:true});openQuickView(cards[index])});
  const closeQuickView=()=>{quickView.close();document.body.classList.remove('quick-view-open');returnFocus?.focus()};
  cards.forEach(card=>{card.addEventListener('click',event=>{if(event.target.closest('.preview-arrows'))return;const active=[...card.querySelectorAll('.sheet-view')].findIndex(img=>img.classList.contains('is-active'));openQuickView(card,Math.max(active,0))});card.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();openQuickView(card)}})});
  quickView.querySelector('.quick-view-close').onclick=closeQuickView;quickView.querySelector('.quick-view-arrow.previous').onclick=()=>showQuickView(quickIndex-1);quickView.querySelector('.quick-view-arrow.next').onclick=()=>showQuickView(quickIndex+1);quickView.addEventListener('click',event=>{if(event.target===quickView)closeQuickView()});quickView.addEventListener('close',()=>document.body.classList.remove('quick-view-open'));stage.addEventListener('touchstart',event=>{quickTouchStart=event.changedTouches[0].clientX},{passive:true});stage.addEventListener('touchend',event=>{const distance=event.changedTouches[0].clientX-quickTouchStart;if(Math.abs(distance)>42)showQuickView(quickIndex+(distance<0?1:-1))},{passive:true});
  const scrollToSelection=()=>{const target=storySection.hidden?main.querySelector('#collection'):storySection;target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})};
  areaButtons.forEach(b=>b.onclick=()=>{applyFilter(b.dataset.area,{updateUrl:true});scrollToSelection()});typeLinks.forEach(l=>l.onclick=e=>{e.preventDefault();applyFilter(l.dataset.filter,{updateUrl:true});scrollToSelection()});const requestedFilter=location.hash.slice(1),initialFilter=requestedFilter||(info.types.length===1?info.types[0][1]:'all');applyFilter(initialFilter);if(requestedFilter)requestAnimationFrame(()=>requestAnimationFrame(scrollToSelection));addEventListener('hashchange',()=>{const filter=location.hash.slice(1)||(info.types.length===1?info.types[0][1]:'all');applyFilter(filter);if(location.hash)scrollToSelection()});
}
